### ISSUE TITLE
Games available after 2014-01-14

### ISSUE THREAD

**Issue by benjh33** [cpsievert/bbscrapeR#3]
If this is just a mining problem, I'm pulling the codes for the NBA games right now. I can send you the updated codes as text or an updated .rda file, if you like.

**Comment by cpsievert** [comment]
That would be awesome!! 

I actually collected codes over a year ago now and forgot how I did it :(

Note that `rebound()` has a `codes` argument. So, you should be able to feed those codes in directly instead of specify a `first` and `last` date.

**Comment by benjh33** [comment]
Ah, yes. I'll do that instead.

I'll get the codes (using basketball-reference.com - all in one tidy table) and send them your way with my kludgy python script.

**Comment by cpsievert** [comment]
Wonderful, thanks!
